import "dotenv/config";
import * as fs from "node:fs";
import * as path from "node:path";
import { createClient } from "@libsql/client";
import { Pool } from "pg";
import { SeriesState } from "../src/state/seriesState.js";

async function cleanupSeries21Episode3() {
  console.log("==================================================");
  console.log("🧹 Starting Cleanup for Series 21, Episode 3");
  console.log("==================================================\n");

  // 1. Local disk cleanup
  const episode3Dir = path.resolve(process.cwd(), "output", "series_21", "episode_3");
  console.log(`📁 Checking local disk path: ${episode3Dir}`);
  if (fs.existsSync(episode3Dir)) {
    console.log(`  Deleting directory recursively: ${episode3Dir}`);
    fs.rmSync(episode3Dir, { recursive: true, force: true });
    console.log("  ✓ Local disk files for episode 3 deleted successfully.\n");
  } else {
    console.log("  ℹ Episode 3 directory does not exist on disk.\n");
  }

  // 2. Turso database cleanup
  const tursoUrl = process.env.TURSO_DATABASE_URL;
  const tursoAuthToken = process.env.TURSO_AUTH_TOKEN ?? "";

  if (!tursoUrl) {
    throw new Error("TURSO_DATABASE_URL environment variable is missing.");
  }

  const turso = createClient({ url: tursoUrl, authToken: tursoAuthToken });
  try {
    console.log("🗄️ Updating Turso database (Series 21, Episode 3)...");

    // Reset episode 3 in episodes table
    const epUpdateRes = await turso.execute({
      sql: `UPDATE episodes
            SET status = 'pending',
                script_json = NULL,
                output_path = NULL,
                updated_at = datetime('now')
            WHERE series_id = 21 AND episode_number = 3`,
    });
    console.log(`  ✓ Updated episode 3 status to 'pending' (rows affected: ${epUpdateRes.rowsAffected})`);

    // Delete episode 3 key art
    const keyArtDeleteRes = await turso.execute({
      sql: `DELETE FROM key_art
            WHERE series_id = 21 AND art_type = 'episode' AND episode_number = 3`,
    });
    console.log(`  ✓ Deleted episode 3 key art from key_art table (rows affected: ${keyArtDeleteRes.rowsAffected})\n`);

    // Verification queries in Turso
    console.log("🔍 Verifying Turso State:");
    const epRes = await turso.execute({
      sql: "SELECT id, series_id, episode_number, title, status, output_path FROM episodes WHERE series_id = 21 AND episode_number <= 5 ORDER BY episode_number",
    });
    for (const r of epRes.rows) {
      console.log(`  Episode ${r.episode_number}: "${r.title}" [status: ${r.status}, output: ${r.output_path}]`);
    }

    const keyArtRes = await turso.execute({
      sql: "SELECT id, series_id, art_type, episode_number, selected_path FROM key_art WHERE series_id = 21",
    });
    console.log("\n  Remaining Key Art entries for Series 21:");
    for (const r of keyArtRes.rows) {
      console.log(`  - KeyArt id ${r.id}: artType=${r.art_type}, episodeNumber=${r.episode_number}`);
    }

  } finally {
    await turso.close();
  }

  // Verify getNextEpisode returns Episode 3
  const seriesState = new SeriesState();
  try {
    const nextEp = await seriesState.getNextEpisode(21);
    console.log("\n🎯 Next Episode to be generated by SeriesState.getNextEpisode(21):");
    if (nextEp) {
      console.log(`  ✓ Episode ${nextEp.episodeNumber}: "${nextEp.title}" (status: ${nextEp.status}, id: ${nextEp.id})`);
    } else {
      console.error("  ❌ Unexpected: getNextEpisode(21) returned null!");
    }
  } finally {
    await seriesState.close();
  }

  // 3. Neon database cleanup (Framework run & checkpoint state)
  if (process.env.NEON_DATABASE_URL) {
    console.log("\n🗄️ Cleaning framework state in Neon database...");
    const pool = new Pool({ connectionString: process.env.NEON_DATABASE_URL });
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query("DELETE FROM checkpoint_writes");
      await client.query("DELETE FROM checkpoints");
      await client.query("DELETE FROM agent_events");
      await client.query("DELETE FROM agent_todos");
      await client.query("DELETE FROM agent_custom_state");
      await client.query("DELETE FROM agent_runs");
      await client.query("COMMIT");
      console.log("  ✓ Cleared Neon checkpoint_writes, checkpoints, agent_events, agent_todos, agent_custom_state, agent_runs");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
      await pool.end();
    }
  }

  console.log("\n==================================================");
  console.log("✅ Cleanup Complete! Series 21 will now restart from Episode 3.");
  console.log("==================================================");
}

cleanupSeries21Episode3().catch((err) => {
  console.error("❌ Cleanup failed:", err);
  process.exit(1);
});
